# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Checklist_Item')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
