# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone2',
        ),
        migrations.AddField(
            model_name='phone',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AddField(
            model_name='email',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
